In [ ]:
#импортируем библиотеки
import torch
import numpy as np

In [ ]:
torch.zeros([3,4])

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
torch.ones([3, 4, 2])

tensor([[[1., 1.],
         [1., 1.],
         [1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.],
         [1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.],
         [1., 1.],
         [1., 1.]]])

In [ ]:
x = torch.Tensor([[1,  2,  3,  4],
              [5,  6,  7,  8],
              [9, 10, 11, 12]])

In [ ]:
mask = x > 3
x[mask]

tensor([ 4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.])

In [ ]:
#shallow-копирование: в реальности копирования не происходит, в один объект другой записывается 
#как реально копировать:
y = x.clone()

In [ ]:
x = x.double()
print(x)
x = x.int()
print(x)
x = x.float()
print(x)

tensor([[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.]], dtype=torch.float64)
tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]], dtype=torch.int32)
tensor([[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.]])


In [ ]:
# np в тензор торча
x = np.array([[1, 2, 3, 4],
              [4, 3, 2, 1]])
x = torch.from_numpy(x)
x

tensor([[1, 2, 3, 4],
        [4, 3, 2, 1]])

In [ ]:
#vice versa
x = x.numpy()
x

array([[1, 2, 3, 4],
       [4, 3, 2, 1]])

In [ ]:
torch.cuda.is_available()
#нет гпу, только цпу

False

In [ ]:
#неделя 2
#train - используем для обучения
#valid - подстраивать параметры сети
#test - проверяем окончательный датасет

#сеть нейронная:
#архитектура, лосс, метод оптимизации
#метрики (не будут влиять на обучение; показывают, как хорошо решаем задачу)


In [ ]:
x = torch.tensor(
    [[1.,  2.,  3.,  4.],
     [5.,  6.,  7.,  8.],
     [9., 10., 11., 12.]], requires_grad=True)

#######
device = torch.device('cuda:0' 
                      if torch.cuda.is_available() 
                      else 'cpu')
x = x.to(device)
#######

function = 10 * (x ** 2).sum()

function.backward()

print(x.grad, '<- gradient')

tensor([[ 20.,  40.,  60.,  80.],
        [100., 120., 140., 160.],
        [180., 200., 220., 240.]]) <- gradient


In [ ]:
u = torch.tensor(
[[5., 10.], [1., 2.]], requires_grad = True)
func = torch.prod(torch.log(torch.log(u + 7))).sum()
func.backward()

print(u.grad, '<- gradient')

tensor([[0.0201, 0.0109],
        [0.0449, 0.0351]]) <- gradient
